### ISSUE TITLE
Using /up misaligns building parts and fills up your entity count with invisible entities.

### ISSUE THREAD

**Issue by SmellyFishRW** [PRISM-Servers/issue-reporting#2]
Doing /up does the building animation even on already upgraded blocks, which moves them a few pixels forward causing misalignment, holes in the wall and inability to build off of them due to entity counts being filled (Error message on chat appears: "You cannot build anymore! You've reached the maximum entity count (0)"
Rotating a wall fixes the misalignment, rotating a door frame/window frame does not. Foundations and floors cannot be rotated, thus they remain bugged forever.

**Comment by Shady7557** [comment]
I believe this is fixed; closing.
