### ISSUE TITLE
Inferior Facepunch backpacks break charms after server restart

### ISSUE THREAD

**Issue by SmellyFishRW** [PRISM-Servers/issue-reporting#3]
If a player puts charms inside a facepunch 🤮backpack, upon server restart the charms no longer work. Similar bug to the older bug where charms inside boxes were cleared after server restart as well
![image](https://github.com/PRISM-Servers/issue-reporting/assets/46636151/acf12163-1e6d-4e8d-9da8-b8a0ba96809d)
![image](https://github.com/PRISM-Servers/issue-reporting/assets/46636151/cb652979-82cb-4538-a749-829efda12fc1)
![image](https://github.com/PRISM-Servers/issue-reporting/assets/46636151/a09b5c96-13e7-4e6f-ae0d-780554323021)

**Comment by Shady7557** [comment]
I've pushed an update to try and address this issue; should be fixed.
