### ISSUE TITLE
Mercenary's Overdrive ability doesn't seem to aim vertically.

### ISSUE THREAD

**Issue by SmellyFishRW** [PRISM-Servers/issue-reporting#6]
This makes shooting NPCs above or below you a hassle, since your aim will just snap directly in front of you as presented in this video

https://cdn.discordapp.com/attachments/1026849381808341022/1208768084077187152/overdrive_bug.mp4?ex=65e47c01&is=65d20701&hm=7361518d2c14c1c32b1fa8a7914ce9376983a1cec8b52489744b369dc766d493&

**Comment by Shady7557** [comment]
Disabled auto aiming; still acts the same way, just no camera movement.
